/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isd_project;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Abidh
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        terminalPanel = new javax.swing.JPanel();
        terminal = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        aboutTerminal = new javax.swing.JPanel();
        feedback = new javax.swing.JLabel();
        feedbackTerminal = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        logoutTerminal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        crossiconPanel = new javax.swing.JPanel();
        crossicon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 0, 40));

        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        jPanel4.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));

        terminalPanel.setBackground(new java.awt.Color(255, 51, 51));
        terminalPanel.setPreferredSize(new java.awt.Dimension(0, 40));

        javax.swing.GroupLayout terminalPanelLayout = new javax.swing.GroupLayout(terminalPanel);
        terminalPanel.setLayout(terminalPanelLayout);
        terminalPanelLayout.setHorizontalGroup(
            terminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        terminalPanelLayout.setVerticalGroup(
            terminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(terminalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 0, 40));

        terminal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terminalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                terminalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                terminalMouseExited(evt);
            }
        });
        jPanel4.add(terminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 30));

        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutMouseExited(evt);
            }
        });
        jPanel4.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 30));

        aboutTerminal.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout aboutTerminalLayout = new javax.swing.GroupLayout(aboutTerminal);
        aboutTerminal.setLayout(aboutTerminalLayout);
        aboutTerminalLayout.setHorizontalGroup(
            aboutTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        aboutTerminalLayout.setVerticalGroup(
            aboutTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(aboutTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 0, 40));

        feedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                feedbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                feedbackMouseExited(evt);
            }
        });
        jPanel4.add(feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 40));

        feedbackTerminal.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout feedbackTerminalLayout = new javax.swing.GroupLayout(feedbackTerminal);
        feedbackTerminal.setLayout(feedbackTerminalLayout);
        feedbackTerminalLayout.setHorizontalGroup(
            feedbackTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        feedbackTerminalLayout.setVerticalGroup(
            feedbackTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(feedbackTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 0, 40));

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel4.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 30));

        logoutTerminal.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout logoutTerminalLayout = new javax.swing.GroupLayout(logoutTerminal);
        logoutTerminal.setLayout(logoutTerminalLayout);
        logoutTerminalLayout.setHorizontalGroup(
            logoutTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        logoutTerminalLayout.setVerticalGroup(
            logoutTerminalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(logoutTerminal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 0, 40));

        jLabel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 260, 580));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 560));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 140, 160));

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, 160));

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 140, 160));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, 160));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 160));

        crossiconPanel.setBackground(new java.awt.Color(255, 255, 255));

        crossicon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        crossicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crossicon.setText("X");
        crossicon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossiconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crossiconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crossiconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout crossiconPanelLayout = new javax.swing.GroupLayout(crossiconPanel);
        crossiconPanel.setLayout(crossiconPanelLayout);
        crossiconPanelLayout.setHorizontalGroup(
            crossiconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crossicon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        crossiconPanelLayout.setVerticalGroup(
            crossiconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crossicon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(crossiconPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 50, 50));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 570, 560));

        setSize(new java.awt.Dimension(827, 558));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        // TODO add your handling code here:
        homePanel.setSize(50, 40);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        // TODO add your handling code here:
        homePanel.setSize(0, 40);
    }//GEN-LAST:event_HomeMouseExited

    private void terminalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminalMouseEntered
        // TODO add your handling code here:
        terminalPanel.setSize(50, 40);
    }//GEN-LAST:event_terminalMouseEntered

    private void terminalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminalMouseExited
        // TODO add your handling code here:
        terminalPanel.setSize(0, 40);
    }//GEN-LAST:event_terminalMouseExited

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
        // TODO add your handling code here:
        aboutTerminal.setSize(50, 40);
    }//GEN-LAST:event_aboutMouseEntered

    private void aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseExited
        // TODO add your handling code here:
        aboutTerminal.setSize(0, 40);
    }//GEN-LAST:event_aboutMouseExited

    private void feedbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseEntered
        // TODO add your handling code here:
        feedbackTerminal.setSize(50, 40);
    }//GEN-LAST:event_feedbackMouseEntered

    private void feedbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseExited
        // TODO add your handling code here:
        feedbackTerminal.setSize(0, 40);
    }//GEN-LAST:event_feedbackMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logoutTerminal.setSize(50, 40);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logoutTerminal.setSize(0, 40);
    }//GEN-LAST:event_logoutMouseExited

    private void crossiconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossiconMouseEntered
        // TODO add your handling code here:
        crossiconPanel.setBackground(Color.red);
    }//GEN-LAST:event_crossiconMouseEntered

    private void crossiconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossiconMouseExited
        // TODO add your handling code here:
        crossiconPanel.setBackground(Color.white);
    }//GEN-LAST:event_crossiconMouseExited

    private void crossiconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossiconMouseClicked
        // TODO add your handling code here:
        System.exit(0);
        this.dispose();
    }//GEN-LAST:event_crossiconMouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        AboutUs a = new AboutUs();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_aboutMouseClicked

    private void feedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackMouseClicked
        // TODO add your handling code here:
        Feedback f = new Feedback();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_feedbackMouseClicked

    private void terminalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminalMouseClicked
        // TODO add your handling code here:
        Terminal t = new Terminal();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_terminalMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        MMS mm = new MMS();
        mm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        CPU_sc cp = new CPU_sc();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Contigious cg = new Contigious();
        cg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        FileAllock fa = new FileAllock();
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Do you want to LogOut?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            Login l = new Login();
            l.setVisible(true);
            this.dispose();
        } else {
            
        }
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Home;
    private javax.swing.JLabel about;
    private javax.swing.JPanel aboutTerminal;
    private javax.swing.JLabel crossicon;
    private javax.swing.JPanel crossiconPanel;
    private javax.swing.JLabel feedback;
    private javax.swing.JPanel feedbackTerminal;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel logoutTerminal;
    private javax.swing.JLabel terminal;
    private javax.swing.JPanel terminalPanel;
    // End of variables declaration//GEN-END:variables
}
